{
  imports = [
    ./kanidm.nix
    ./traefik.nix
    ./vaultwarden.nix
    ./smb.nix
    ./jellyfin.nix
    ./postgres.nix
    ./netbird/main.nix
    ./dashy.nix
    ./paperless.nix
    ./lidarr.nix
    ./zrepl.nix
    ./homeassistant.nix
    ./grafana.nix
    ./alloy.nix
    ./mimir.nix
    ./loki.nix
    ./minecraft.nix
    ./wazuh.nix
    ./wazuh-docker.nix
    ./timekpr-webui.nix
    ./actual.nix
    ./ollama.nix
  ];
}
